import Head from "next/head";
import { Inter } from "next/font/google";
import Home from "./home";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Index({ categoryList, productList }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home categoryList={categoryList} productList={productList} />
    </>
  );
}

export const getServerSideProps = async () => {
  const resCategories = await axios.get(
    `${process.env.NEXT_PUBLIC_API_URL}/categories`
  );
  const resProducts = await axios.get(
    `${process.env.NEXT_PUBLIC_API_URL}/products`
  );
  return {
    props: {
      categoryList: resCategories?.data ? resCategories.data : [],
      productList: resProducts?.data ? resProducts.data : [],
    },
  };
};
